


# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fabian Alcantara
email: hello@fabuloso.me
description: > # this means to ignore newlines until "baseurl:"
  Why I want to join GitHub as Web Designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fabuloso
github_username:  fabalca


# Build settings
markdown: kramdown
 input: GFM #using GitHub Markdown
sass:
  sass_dir: _sass
include: ['_pages']


# This project is based on the Hyde Theme by mdo (https://github.com/mdo).
##############################################
# It is set up as a static website (no blog) and converted using SASS.

# Help from: https://www.taniarascia.com/make-a-static-website-with-jekyll/ on structure setup and making
# a static website.

# Help from: https://webdesign.tutsplus.com/courses/building-static-websites-with-jekyll/

# Help from: https://www.sitepoint.com/set-jekyll-blog-5-minutes-poole/

# Help from: https://www.youtube.com/watch?v=iWowJBRMtpc


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Title of your Site
email: Your email
description: > # this means to ignore newlines until "baseurl:"
Give a description of what this website is for.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twitter_username
github_username:  github_username


# Build settings
markdown: kramdown
 input: GFM
sass:
  sass_dir: _sass
include: ['_pages']